# Common configuration.
AllCops:

  Exclude:
    - sample_option_price_output.rb
    - 'log/*'
    - 'tmp/**/*'
    - '.DS_Store'
    - 'public/assets/*'
    - 'public/503.html'
    - '.env'
    - '*.pem'
    - '*.orig'
    - 'lib/templates/rails/**/*'
    - db/schema.rb
    - bin/setup
    - bin/*

Documentation:

  Enabled: false
